#!/bin/bash

echo "selamat datang"

termux-open https://wa.me/+6285731928045?text=kak+izin+gunain+script+mu+

echo "masukkan kode scriptnya"

sleep 10

echo "kode scriptnya {Ridwan}"

read -p "root@Kode Script > " bro

if [ $bro = Ridwan ] || [ $bro = Ridwan ]

then

sleep 2

clear

sh Ridwan2

fi
