#!/bin/bash

echo "selamat datang"

termux-open https://wa.me/+6285731928045?text=kak+izin+gunain+script+mu+

echo "masukkan kode scriptnya"

sleep 2

echo "kode scriptnya {567686}"

read -p "root@Kode Script > " bro

if [ $bro = 567686 ] || [ $bro = 567686 ]

then

sleep 2

clear

sh Ridwan2

fi
