#!/system/xbin/bash
#mau Recode izin dulu di Instagram Ridwan58aja
#Github:https://github.com/RidwanKechil
blu='\e[1;34m'
green='\e[1;32m'
purple='\[1;35m'
cyan='\e[1;36m'
red='\e[1;31m'
white='\e[1;37m'
yellow='\e[1;33m'
steep 0,01
echo
echo
clear

cd /sdcard
sleep 0.01
echo "\033[32;1m Subscribe dulu"
echo "membuka YouTube" 
termux-open https://www.youtube.com/channel/UCTMBlJoMW9jaWyiv8oZsjKw
sleep 1
echo " login berhasil "
echo
echo
clear

sleep 1
echo "\033[32;1m selamat datang siapa nama kamu?" #tulisankeluar
read nick #membaca tulisan
echo
echo
clear

sleep 3
echo "\033[32;1m
#################################
#-AUTHOR= RIDWAN-KECHIL.. #
#-subs. = Ridwan Kechil. #
#-Team=THEIMMORTALHACKER #
#################################"
sleep 1
echo "SELAMAT BERGABUNG" $nick
echo "---------------------------------------------"
sleep 2
echo "|Subscribe dulu broo"
sleep 2
echo "|Nama Channel gw"
sleep 2
echo "|Ridwan Kechil"
sleep 1
echo "|instagram gw nih"
echo "|Ridwan58aja"
sleep 1
echo "~~~~~~~~~~~~~~~~~~~~~ -"
sleep 1
echo "Subscribe dulu untuk melanjutkan klik [Ok] "
read p;
sleep 1
echo "Terimakasih" $nick
sleep 2
echo "\033[32;1m
cara untuk melanjutkan scriptnya
Subscribe dulu broo kalo gak subscribe script ini gak akan berfungsi dalam hp anda
ikuti langkah langkah nya
1. buka fb kalian
2. cari akun target
3. buka profil target
4. salin tautan profile
5.tempel tautan di bawah ini"
sleep 1
echo "\033[32;1mdisini>" #tulisankeluar
read nick1; #membaca tulisan
sleep 2
echo
echo
clear

sleep 3
echo "\033[32;1m
#################################
#-AUTHOR= RIDWAN-KECHIL.. #
#-subs. = Ridwan Kechil. #
#-Team=THEIMMORTALHACKER #
################################# "
sleep 1
echo "masukkan nomor hp anda "
echo "\033[32;1m100%Aman "
read p;
sleep 3
echo
echo
clear

echo "\033[32;1m install bahan dulu broo"
echo "[y] klik y untuk melanjutkan"
read p;
sleep 2
echo "Sabar broo Progses tunggu sampai selesai..."
echo "\033[34;1m#10%"
sleep 1
echo "##20%"
sleep 1
echo "###30%"
sleep 1
echo "####40%"
sleep 2
echo "#####50%"
sleep 3
echo "######60%"
sleep 6
echo "#######70%"
sleep 8
echo "########80%"
sleep 10
echo "#########90%"
sleep 16
echo "##########100%"
echo "---------------------------->>>>>>"
echo "progses di mulai"
echo "\033[32;1mmau melanjutkan [y] "
read p;
echo
echo
clear

sleep 3
echo "\033[32;1m
#################################
#-AUTHOR= RIDWAN-KECHIL.. #
#-subs. = Ridwan Kechil. #
#-Team=THEIMMORTALHACKER #
################################# "
sleep 1
echo "sabar tunggu beberapa menit"
sleep 4
echo "_____________________________________"
sleep 2
echo "Pencarian berkas"
sleep 2
echo "#10%"
sleep 1
echo "#######""100%"
sleep 3
echo "estrak" "." "." "."
sleep 2
echo "estrak file Anda"
sleep 1
echo "tunggu sampai selesai"
sleep 4
echo "_0%"
sleep 1
echo "##_20%"
sleep 2
echo "####_40%"
sleep 3
echo "######_60%"
sleep 4
echo "########_80%"
sleep 8
echo "##########_100%"
sleep 4
echo "____________________________________"
sleep 2
echo "berhasil"
sleep 1
echo "\033[32;1mscript aktif"
sleep 1
echo "kata sandi anda "
sleep 6
echo "Gmail" $nick1
echo "\033[31;1m===>>>    sandi =>> Odadingmah123"
sleep 1
echo "kata sandi aktif "
echo "___________________________________ "
sleep 1
echo "file di hapus silahkan coba semoga work "
echo "dan jangan lupa untuk kembali "
echo "sandi akan hilang dalam waktu 120 detik "
sleep 120
echo
echo
clear

sleep 1
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "jangan lupa kembali & semoga berhasil"
